# Generated by Django 2.2.5 on 2019-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_auto_20190914_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.CharField(max_length=128),
        ),
    ]
