# Generated by Django 2.2.5 on 2019-09-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BazaDanych',
            new_name='Artykul',
        ),
    ]
